apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: job-scheduler
spec:
  type: ClusterIP
  selector:
    app: job-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
