apiVersion: v1
kind: Secret
metadata:
  name: job-consumer-db-secret
  namespace: job-scheduler
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/JobDB
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
