# -----------------------------
# 3. StatefulSet
# -----------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  namespace: job-scheduler
spec:
  serviceName: tempo
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      nodeSelector:
        node-type: monitoring
      containers:
        - name: tempo
          image: grafana/tempo:2.4.1
          args:
            - "-config.file=/etc/tempo/tempo.yaml"   # 🔴 REQUIRED
          ports:
            - containerPort: 3200
            - containerPort: 9411
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo/tempo.yaml
              subPath: tempo.yaml
            - name: tempo-storage
              mountPath: /var/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
  volumeClaimTemplates:
    - metadata:
        name: tempo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi