# ClusterIP Service (used by apps)

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: job-scheduler
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

# Applications use:
# postgres.job-scheduler.svc.cluster.local:5432
