apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: job-scheduler
data:
  grafana-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:4317

  grafana-dashboard-provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: 'Default'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/dashboards
