apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobservice-pvc
  namespace: job-scheduler
spec:
  accessModes:
    - ReadWriteMany   # Allows multiple pods to read/write the volume
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
