apiVersion: v1
kind: Namespace
metadata:
  name: job-scheduler
  labels:
    app.kubernetes.io/part-of: job-platform
    environment: base
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    app.kubernetes.io/part-of: job-platform
    environment: base
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: job-platform
    environment: base
