apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: ""
resources:
  - ../../base
patches:
  - path: patches/dev-storage-class.yaml
  - path: patches/dev-ingress.yaml
  - path: patches/dev-replicas.yaml
images:
  - name: boroleujval4/api-gateway
    newTag: 1.0.0
  - name: boroleujval4/job-service
    newTag: 1.0.0
  - name: boroleujval4/job-consumersvc
    newTag: 1.0.0
  - name: boroleujval4/job-schedulersvc
    newTag: 1.0.0
  - name: boroleujval4/job-cronexecutor
    newTag: 1.0.0
  - name: boroleujval4/job-manualexecutor
    newTag: 1.0.0
