apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: job-scheduler
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017



#       Apps inside cluster connect using:

# mongodb.job-scheduler.svc.cluster.local:27017