apiVersion: v1
kind: ConfigMap
metadata:
  name: job-scheduler-config
  namespace: job-scheduler
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"

---